In [2]:
import numpy as np
import pandas as pd

# Task 1 - Download data

‘Graduate Employment Survey - NTU, NUS, SIT, SMU, SUSS & SUTD’ data was downloaded from the [Data.gov.sg](Data.gov.sg) website.

# Task 2 - Read the data

In [83]:
#Loading the data into a Pandas dataframe
df = pd.read_csv("GraduateEmploymentSurveyNTUNUSSITSMUSUSSSUTD.csv", encoding='latin-1')  # specfiy latin-1 encoding to read the data

df.head()

,year,university,school,degree,employment_rate_overall,employment_rate_ft_perm,basic_monthly_mean,basic_monthly_median,gross_monthly_mean,gross_monthly_median,gross_mthly_25_percentile,gross_mthly_75_percentile
0,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy and Business,97.4,96.1,3701,3200,3727,3350,2900,4000
1,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy (3-yr direct Honours Programme),97.1,95.7,2850,2700,2938,2700,2700,2900
2,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business (3-yr direct Honours Programme),90.9,85.7,3053,3000,3214,3000,2700,3500
3,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business and Computing,87.5,87.5,3557,3400,3615,3400,3000,4100
4,2013,Nanyang Technological University,College of Engineering,Aerospace Engineering,95.3,95.3,3494,3500,3536,3500,3100,3816

# Task 3 - A quick peek

## Info

In [3]:
df.info()       # gives summary of df, to see the various columns, data type they contain, and number of data points present

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1262 entries, 0 to 1261
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   year                       1262 non-null   int64
 1   university                 1262 non-null   object
 2   school                     1262 non-null   object
 3   degree                     1262 non-null   object
 4   employment_rate_overall    1262 non-null   object
 5   employment_rate_ft_perm    1262 non-null   object
 6   basic_monthly_mean         1262 non-null   object
 7   basic_monthly_median       1262 non-null   object
 8   gross_monthly_mean         1262 non-null   object
 9   gross_monthly_median       1262 non-null   object
 10  gross_mthly_25_percentile  1262 non-null   object
 11  gross_mthly_75_percentile  1262 non-null   object
dtypes: int64(1), object(11)
memory usage: 118.4+ KB

## Head

In [4]:
df.head()    # To see the first 5 rows by default

,year,university,school,degree,employment_rate_overall,employment_rate_ft_perm,basic_monthly_mean,basic_monthly_median,gross_monthly_mean,gross_monthly_median,gross_mthly_25_percentile,gross_mthly_75_percentile
0,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy and Business,97.4,96.1,3701,3200,3727,3350,2900,4000
1,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy (3-yr direct Honours Programme),97.1,95.7,2850,2700,2938,2700,2700,2900
2,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business (3-yr direct Honours Programme),90.9,85.7,3053,3000,3214,3000,2700,3500
3,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business and Computing,87.5,87.5,3557,3400,3615,3400,3000,4100
4,2013,Nanyang Technological University,College of Engineering,Aerospace Engineering,95.3,95.3,3494,3500,3536,3500,3100,3816

## Shape

In [5]:
df.shape   # gives a tuple representing the number of rows and columns of the df

(1262, 12)

# Task 4 - Data Cleaning

1. Shortening Names for the Universities
2. Replacing "na" with np.nan

In [6]:
df['university'].unique()         # Checking the unique university names present

array(['Nanyang Technological University',
       'National University of Singapore',
       'Singapore Management University',
       'Singapore Institute of Technology',
       'Singapore University of Technology and Design',
       'Singapore University of Social Sciences'], dtype=object)

In [88]:
replace_info = {'Nanyang Technological University': 'NTU',
                'National University of Singapore': 'NUS',
                'Singapore Management University': 'SMU',
                'Singapore Institute of Technology': 'SIT',
                'Singapore University of Technology and Design': 'SUTD',
                'Singapore University of Social Sciences': 'SUSS',           # Dictionary matching the full University names to abbreviated form, to change names
                'na': np.nan,
               'np.nan': np.nan}               # Dictionary matching "na" and "np.nan" to np.nan, to change str to np.nan           

#using dictionary above, replace full University names with abbreviation, replace "na" and "np.nan" to np.nan
df.replace(to_replace=replace_info, inplace=True)

In [89]:
(df=='na').sum().sum()

np.int64(0)

In [9]:
df.iloc[0:25,0:5]    # Checking if changes are made

,year,university,school,degree,employment_rate_overall
0,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy and Business,97.4
1,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy (3-yr direct Honours Programme),97.1
2,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business (3-yr direct Honours Programme),90.9
3,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business and Computing,87.5
4,2013,Nanyang Technological University,College of Engineering,Aerospace Engineering,95.3
5,2013,Nanyang Technological University,College of Engineering,Bioengineering,81.3
6,2013,Nanyang Technological University,College of Engineering,Chemical and Biomolecular Engineering,87.3
7,2013,Nanyang Technological University,College of Engineering,Computer Engineering,90.3
8,2013,Nanyang Technological University,College of Engineering,Civil Engineering,94.8
9,2013,Nanyang Technological University,College of Engineering,Computer Science,92.1
10,2013,Nanyang Technological University,College of Engineering,Electrical and Electronic Engineering,91
11,2013,Nanyang Technological University,College of Engineering,Environmental Engineering,84
12,2013,Nanyang Technological University,College of Engineering,Information Engineering and Media,85.7
13,2013,Nanyang Technological University,College of Engineering,Materials Engineering,82.5
14,2013,Nanyang Technological University,College of Engineering,Mechanical Engineering,91.6
15,2013,Nanyang Technological University,College of Engineering,Maritime Studies,95.6
16,2013,Nanyang Technological University,"College of Humanities, Arts & Social Sciences","Art, Design & Media",81.6
17,2013,Nanyang Technological University,"College of Humanities, Arts & Social Sciences",Chinese,85.1
18,2013,Nanyang Technological University,"College of Humanities, Arts & Social Sciences",Communication Studies,89.4
19,2013,Nanyang Technological University,"College of Humanities, Arts & Social Sciences",Economics,89.9
20,2013,Nanyang Technological University,"College of Humanities, Arts & Social Sciences",English,82.7
21,2013,Nanyang Technological University,"College of Humanities, Arts & Social Sciences",Linguistics and Multilingual Studies,90.6
22,2013,Nanyang Technological University,"College of Humanities, Arts & Social Sciences",Psychology,82.4
23,2013,Nanyang Technological University,"College of Humanities, Arts & Social Sciences",Sociology,74.4
24,2013,Nanyang Technological University,College of Sciences,Biomedical Sciences **,na

3. Changing basic_monthly_median type to float.

In [74]:
df.info()        # Checking what type it is

<class 'pandas.core.series.Series'>
MultiIndex: 52 entries, ('NTU', '2013.0') to ('SUTD', '2022.0')
Series name: basic_monthly_mean
Non-Null Count  Dtype
--------------  -----
52 non-null     float64
dtypes: float64(1)
memory usage: 916.0+ bytes

In [93]:
# Changing column Dtype from object to float
new_type_info = {'basic_monthly_mean': 'float'}
df = df.astype(new_type_info)
df = df.astype({'degree':'str'})
df.info()      # Checking if changes are made

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1262 entries, 0 to 1261
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   year                       1262 non-null   object
 1   university                 1262 non-null   object
 2   school                     1230 non-null   object
 3   degree                     1262 non-null   object
 4   employment_rate_overall    1170 non-null   object
 5   employment_rate_ft_perm    1170 non-null   object
 6   basic_monthly_mean         1170 non-null   float64
 7   basic_monthly_median       1170 non-null   object
 8   gross_monthly_mean         1170 non-null   object
 9   gross_monthly_median       1170 non-null   object
 10  gross_mthly_25_percentile  1170 non-null   object
 11  gross_mthly_75_percentile  1170 non-null   object
dtypes: float64(1), object(11)
memory usage: 118.4+ KB

### Purpose of shortening Uni name:
- For ease of readability
- Reduce human error in the code

### Purpose of replacing "na" with np.nan:
- Cleaning the df.
- Changing "na" string into np.nan (which is not a number, and is recognised as null value), ensures that the system recognises that it is a missing value, so that .agg() can run - a str would return an error, but nan is acceptable, and skipped in .agg().
- This is because pandas operations will skip null values by default.

## Purpose of changing column type from object into float:
- We need it to be float to calculate the mean, median as needed in Task 5 (mean and median operations cannot be done correctly on objects as they cannot be interpreted as numeric values).
- Float used instead of Int so that precision is kept for values with decimal places.

# Task 5 - Analyse the Data

In [58]:
# Summary statistics based on the values in basic_monthly_median
df['basic_monthly_median'].describe(include='all')

count    1170.000000
mean     3537.801709
std       626.856931
min      1750.000000
25%      3100.000000
50%      3400.000000
75%      3800.000000
max      6500.000000
Name: basic_monthly_median, dtype: float64

In [59]:
# Table of data that shows the minimum, maximum, mean for the basic_monthly_median
x = df.groupby(by=["year", "university"])[['basic_monthly_median']].agg(["count", "min", "max", "mean", "std"]).round(3)

x

                  basic_monthly_median
                                 count     min     max      mean      std
year   university
2013.0 NTU                          32  2500.0  3500.0  3009.562  214.472
       NUS                          33  2650.0  4800.0  3119.030  473.869
       SMU                          12  2800.0  5000.0  3493.750  710.963
2014.0 NTU                          33  2600.0  3700.0  3074.242  212.820
       NUS                          34  2550.0  5000.0  3265.647  505.622
       SIT                          24  2400.0  3355.0  2899.583  270.446
       SMU                          12  2850.0  4900.0  3624.167  653.615
2015.0 NTU                          33  2800.0  4184.0  3153.939  275.999
       NUS                          36  2850.0  4600.0  3389.056  427.337
       SIT                          25  2300.0  3400.0  2958.800  264.434
       SMU                          12  2900.0  4766.0  3630.500  575.910
       SUTD                          3  3450.0  3700.0  3589.333  127.441
2016.0 NTU                          34  2400.0  4000.0  3231.324  282.366
       NUS                          34  2800.0  4775.0  3391.912  445.547
       SIT                          26  2250.0  4200.0  3122.692  406.010
       SMU                          12  3000.0  4950.0  3713.917  597.020
       SUTD                          3  3500.0  4000.0  3700.000  264.575
2017.0 NTU                          35  2800.0  4750.0  3313.057  338.092
       NUS                          37  2025.0  5000.0  3445.486  524.885
       SIT                          28  2300.0  3800.0  3102.679  342.873
       SMU                          12  3000.0  5450.0  3849.500  675.130
       SUTD                          3  3600.0  4000.0  3800.000  200.000
2018.0 NTU                          37  2800.0  4450.0  3410.595  322.758
       NUS                          33  1750.0  5000.0  3531.182  596.037
       SIT                          32  2530.0  4000.0  3274.688  377.406
       SMU                          12  3000.0  4750.0  3850.000  565.685
       SUSS                          3  2850.0  3400.0  3083.333  284.312
       SUTD                          4  3700.0  4300.0  3925.000  262.996
2019.0 NTU                          38  3000.0  4833.0  3526.921  412.544
       NUS                          36  3000.0  5000.0  3736.528  570.829
       SIT                          31  2350.0  4400.0  3396.710  445.579
       SMU                          12  3000.0  5000.0  3963.833  634.741
       SUSS                          4  3000.0  3400.0  3100.000  200.000
       SUTD                          4  3800.0  4400.0  3999.250  271.174
2020.0 NTU                          40  2800.0  5200.0  3638.400  471.346
       NUS                          39  3000.0  5350.0  3895.385  609.244
       SIT                          37  2475.0  5000.0  3487.405  507.024
       SMU                          12  3050.0  5000.0  4005.833  626.265
       SUSS                          7  2750.0  3500.0  3059.000  236.186
       SUTD                          4  3800.0  4500.0  4012.500  332.603
2021.0 NTU                          39  3000.0  6300.0  3765.590  609.554
       NUS                          38  2958.0  5800.0  3967.211  656.449
       SIT                          33  2500.0  5000.0  3556.061  499.337
       SMU                          12  3400.0  5600.0  4369.417  783.333
       SUSS                          8  3000.0  3800.0  3328.750  258.094
       SUTD                          4  3801.0  4800.0  4275.250  457.001
2022.0 NTU                          41  3100.0  6000.0  4110.439  689.419
       NUS                          38  3350.0  6500.0  4404.842  827.763
       SIT                          35  2450.0  5500.0  3914.086  593.001
       SMU                          12  3800.0  6338.0  4711.000  860.401
       SUSS                          8  3100.0  4500.0  3670.625  415.301
       SUTD                          4  4100.0  5000.0  4437.500  415.080

In [105]:
y = df.groupby(by=['degree','university'])[['basic_monthly_mean']].agg(['std'])
y

                                                  basic_monthly_mean
                                                                 std
degree                                 university
Accountancy                            NTU                746.755608
                                       SMU                456.453652
Aerospace Engineering                  NTU                385.629680
Aerospace Engineering and Economics ** NTU                       NaN
Art, Design & Media                    NTU                239.104510
...                                                              ...
Social Sciences (Cum Laude and above)  SMU                288.503899
Social Sciences Cum Laude and above    SMU                258.933067
Sociology                              NTU                261.975190
Sport Science and Management           NTU                       NaN
Sports Science and Management          NTU                219.189416

[342 rows x 1 columns]

In [104]:
for degree in df['degree']:
    if degree.startswith('Accountancy'):
        df.replace(to_replace = {degree:'Accountancy'}, inplace=True)
    else: continue

### Comments on code:
- .groupby() allows us to organise the data in this specified manner, by year, then by University. 
- .agg() is used because we want specific outcomes like count, min, max, mean, std.
- Using .describe() gives us the values above & 25,50,75 percentile, which is not wanted.
- We wanted to customise the output, so we used .agg().
- agg() is for calculating a lot of summary statistics in one line of code rather than np.mean(), np.median()

### Why is this step needed?
- To allow us to obtain information for basic_monthly_median specifically, grouped in this particular manner, so that we can plot the bar graph based on these values, in this grouping.

# Task 6 - Time to plot

In [13]:
import matplotlib.pyplot as plt

In [106]:
df_pivot = df.pivot_table(values='basic_monthly_median', index='year', columns='university', aggfunc='mean')
df_pivot.plot(kind='bar')
plt.ylabel('Median Salary')
plt.xlabel('year')
plt.xticks(rotation=0)
plt.legend(loc=(1.05,0.4))
plt.tight_layout()
plt.show()

TypeError: agg function failed [how->mean,dtype->object]

### Using the column information to plot bar chart
- Allows us to visualise the trend of median salaries of different Universities over time.
- aggfunc function is set as "mean" because we only want to plot the mean value.
- Mean values were presented as they account for all values in the dataset, reflecting the overall distribution. This makes it more useful when analysing trends, compared to the median, which only considers the middle value